@host = http://192.168.0.3:8080
@username = Mat@Hackathon
@password = password
@carId = 67cde85baa05e02849d03853

@header_hackathon = X-HACKATHON: authenticated

### Authenticate API first call
GET {{host}}/api/20250227/pass/67cde85baa05e02849d03853
Authorization: Basic {{username}}:{{password}}
{{header_hackathon}}


### Authenticate API first call
POST {{host}}/api/20250227/pass/generate/67cde85baa05e02849d03853
Authorization: Basic {{username}}:{{password}}
{{header_hackathon}}
